export const libros = [
  {
    id: 1,
    title: 'El Señor de los Anillos: La comunidad del anillo',
    image: 'https://covers.openlibrary.org/b/isbn/9788445071403-M.jpg',
    author: 'J R R Tolkien' ,
    synopsis: 'El joven hobbit Frodo Bolsón, tras heredar un misterioso anillo de su tío Bilbo, deberá abandonar su hogar para evitar que caiga en manos de su malvado creador. En el camino, se forma una comunidad para proteger al portador del anillo y asegurarse de que el anillo llegue a su destino final: Mt. Doom, el único lugar donde puede ser destruido....',
    isbn10: '8445071408',
    isbn13: '9788445071403',
    genre: 'Aventura, Drama, Fantasia',
    rating: 9.9,
},
{
    id: 2,
    title: 'El Señor de los Anillos: Las dos torres',
    image: 'https://covers.openlibrary.org/b/isbn/0606305645-M.jpg',
    author: 'J R R Tolkien' ,
    synopsis: 'La Compañía se ha disuelto y sus integrantes emprenden caminos separados. Frodo y Sam continúan solos su viaje a lo largo del río Anduin, perseguidos por la sombra misteriosa de un ser extraño que también ambiciona la posesión del Anillo.',
    isbn10: '0606305645',
    isbn13: '9780606305648',
    genre: 'Aventura, Drama, Fantasia',
    rating: 9.9,
},
{
    id: 3,
    title: 'El Señor de los Anillos: El Retorno del Rey',
    image: 'https://covers.openlibrary.org/b/isbn/9789505470662-M.jpg',
    author: 'J R R Tolkien' ,
    synopsis: 'Gandalf y Aragorn lideran el Mundo de los Hombres contra el ejército de Sauron para desviar su mirada de Frodo y Sam mientras se acercan al Monte del Destino con el Anillo Único.',
    isbn10: '9505470665',
    isbn13: '9789505470662',
    genre: 'Aventura, Drama, Fantasia',
    rating: 9.9,
},
{
  id: 4,
  title: 'El Hobbit',
  image: 'https://covers.openlibrary.org/b/isbn/9788445074855-M.jpg',
  author: 'J R R Tolkien' ,
  synopsis: 'narra la historia del hobbit Bilbo Bolsón, que junto con el mago Gandalf y un grupo de enanos, vive una aventura en busca del tesoro custodiado por el dragón Smaug en la Montaña Solitaria.',
  isbn10: '8445074857',
  isbn13: '9788445074855',
  genre: 'Aventura, Drama, Fantasia',
  rating: 9.9,
},
];
